### ISSUE TITLE
Don't allow frame max lower than server minimum, or expose server error.

### ISSUE THREAD

**Issue by camelpunch** [rabbitmq/rabbitmq-objc-client#33]

**Comment by camelpunch** [comment]
It seems Bunny doesn't even do this:

```ruby
irb(main):007:0> c=Bunny.new(frame_max: 10)
=> #<Bunny::Session:0x7fb4e29dabe0 guest@127.0.0.1:5672, vhost=/, addresses=[127.0.0.1:5672]>
irb(main):008:0> c.start
W, [2016-03-01T14:24:30.968319 #9395]  WARN -- #<Bunny::Session:0x7fb4e29dabe0 guest@127.0.0.1:5672, vhost=/, addresses=[127.0.0.1:5672]>: An empty frame was received while opening the connection. In RabbitMQ <= 3.1 this could mean an authentication issue.
Bunny::TCPConnectionFailedForAllHosts: Could not establish TCP connection to any of the configured hosts
	from /Users/pivotal/.gem/ruby/2.2.2/gems/bunny-2.2.2/lib/bunny/session.rb:315:in `rescue in start'
	from /Users/pivotal/.gem/ruby/2.2.2/gems/bunny-2.2.2/lib/bunny/session.rb:281:in `start'
	from (irb):8
	from /Users/pivotal/.rubies/ruby-2.2.2/bin/irb:11:in `<main>'
```

**Comment by michaelklishin** [comment]
I don't think this is a particularly common feature. Let's revisit it if there's evidence that people do try to use such low values in practice. I don't think most should override frame max at all.
