### ISSUE TITLE
TypeError - Unable to convert Ruby value `"CocoaAsyncSocket"' into a CFTypeRef.

### ISSUE THREAD

**Issue by asvechkar** [rabbitmq/rabbitmq-objc-client#86]
Add in my Podfile:

```
pod 'RMQClient', :git => 'git@github.com:rabbitmq/rabbitmq-objc-client.git'
```

When pod install next error:

```
Analyzing dependencies
Pre-downloading: `RMQClient` from `git@github.com:rabbitmq/rabbitmq-objc-client.git`
Downloading dependencies
Installing CocoaAsyncSocket (7.4.3)
Using Font-Awesome-Swift (1.4.7)
Installing JKVValue (1.3.1)
Using LiquidFloatingActionButton (0.1.1)
Installing RMQClient (0.7.1)
Generating Pods project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/asvechkar/.rvm/rubies/ruby-2.2.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.11.6 (15G19a)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/asvechkar/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 051c7d56ee2efe4f0f5497a2eb7ea501366b44d6
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Portalapp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Font-Awesome-Swift', '~> 1.4.7'
  pod 'CocoaAsyncSocket'
  pod 'RMQClient', :git => 'git@github.com:rabbitmq/rabbitmq-objc-client.git'
  # Pods for Portalapp
  pod "LiquidFloatingActionButton", :git => 'https://github.com/yoavlt/LiquidFloatingActionButton.git', :branch => 'swift-2.0'

end
```

### Error

```
TypeError - Unable to convert Ruby value `"CocoaAsyncSocket"' into a CFTypeRef.
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:383:in `RubyValueToCFTypeRef'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:372:in `RubyValueToCFTypeRef'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:372:in `RubyValueToCFTypeRef'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi.rb:103:in `ruby_hash_write_xcode'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist/ffi.rb:40:in `write_to_path'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/plist.rb:46:in `write_to_path'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.0.0/lib/xcodeproj/project.rb:332:in `save'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:696:in `block in write_pod_project'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:144:in `message'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:688:in `write_pod_project'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:173:in `block in generate_pods_project'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:63:in `section'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0/lib/cocoapods/installer.rb:119:in `install!'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0/lib/cocoapods/command/install.rb:37:in `run'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Users/asvechkar/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/Users/asvechkar/.rvm/rubies/ruby-2.2.0/bin/pod:22:in `load'
/Users/asvechkar/.rvm/rubies/ruby-2.2.0/bin/pod:22:in `<main>'
/Users/asvechkar/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/asvechkar/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Unable+to+convert+Ruby+value+%60%22CocoaAsyncSocket%22%27+into+a+CFTypeRef.&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!
```

**Comment by michaelklishin** [comment]
That's a little bit terse. What were you doing that triggered this exception? Can you paste the entire stack trace?

**Comment by michaelklishin** [comment]
Let's take it to rabbitmq-users. There is 0 evidence that this is an actionable client library issue and we do not use GitHub issues for questions.

**Comment by michaelklishin** [comment]
@camelpunch I don't know if this can be a problem with the Cocoa Pods spec. If there is no evidence of that, please close the issue as this seems mailing list material to me.

**Comment by asvechkar** [comment]
I don't how fix this error. I need your help

**Comment by asvechkar** [comment]
What information you need?

**Comment by michaelklishin** [comment]
Please post questions to rabbitmq-users. RabbitMQ uses GitHub issues for specific actionable items engineers can work on, not questions. Thank you.

**Comment by michaelklishin** [comment]
OK, this is clearly turning into something that belongs to the mailing list.

**Comment by michaelklishin** [comment]
@asvechkar a quick Google search reveals [this is a known issue with CocoaPods on Ruby versions < 2.2.3](https://github.com/CocoaPods/CocoaPods/issues/5037).
